apiVersion: apps/v1
kind: Deployment
metadata:
  name: examplec
spec:
  replicas: 1
  selector:
    matchLabels:
      app: examplec
  template:
    metadata:
      labels:
        app: examplec
    spec:
      containers:
      - name: examplec
        image: subaniprasad/nodejs-containerized:v1

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: examplec
  name: examplec
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: examplec
  type: NodePort
